#!/usr/bin/env python3
"""
Check all resource links (preview images, JSON metadata, dataset files) on a
rendered CDCS detail page and report any that return non-200 responses.

Uses Playwright to render the page so that client-side XSLT output is included.

Usage:
    uv run --with playwright python deployment/scripts/check_record_links.py https://nexuslims-demo.localhost/data?id=16
    uv run --with playwright python deployment/scripts/check_record_links.py --all https://nexuslims-demo.localhost
    uv run --with playwright python deployment/scripts/check_record_links.py --ids 1,2,3 https://nexuslims-demo.localhost
"""

from __future__ import annotations

import argparse
import sys
from urllib.parse import urljoin, urlparse

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


# ---------------------------------------------------------------------------
# Link extraction via Playwright
# ---------------------------------------------------------------------------

def get_page_links(url: str, timeout_ms: int = 30000) -> dict[str, list[str]]:
    """Render the page with Playwright and extract resource URLs by category."""
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context(ignore_https_errors=True)
        page = context.new_page()

        page.goto(url, wait_until="networkidle", timeout=timeout_ms)

        # Wait for XSLT representation to appear
        try:
            page.wait_for_selector("#xslt-representation", timeout=10000)
        except Exception:
            pass  # Proceed even if not found

        # Expand all DataTables to show every row so paginated links are in the DOM
        page.evaluate("""
            () => {
                if (typeof $ !== 'undefined' && $.fn && $.fn.dataTable) {
                    $.fn.dataTable.tables({ api: true }).page.len(-1).draw();
                }
            }
        """)
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass

        previews = page.eval_on_selector_all(
            "img[src]",
            "els => els.map(e => e.src).filter(s => s.includes('.thumb.png'))",
        )
        json_links = page.eval_on_selector_all(
            "a[href]",
            "els => els.map(e => e.href).filter(s => s.endsWith('.json'))",
        )
        # Dataset file links: the download <a> in td.aa-dl-col, generated by
        # the XSLT for each nx:location value.
        dataset_links = page.eval_on_selector_all(
            "td.aa-dl-col a[href]",
            "els => els.map(e => e.href).filter(s => s.startsWith('http'))",
        )

        browser.close()

    return {
        "previews": sorted(set(previews)),
        "json": sorted(set(json_links)),
        "datasets": sorted(set(dataset_links)),
    }


# ---------------------------------------------------------------------------
# Link checking
# ---------------------------------------------------------------------------

def check_url(url: str, session: requests.Session) -> tuple[int | None, str]:
    """Return (status_code, error_message). status_code is None on connection error."""
    try:
        resp = session.head(url, allow_redirects=True, timeout=10, verify=False)
        return resp.status_code, ""
    except requests.exceptions.ConnectionError as e:
        return None, f"Connection error: {e}"
    except requests.exceptions.Timeout:
        return None, "Timeout"
    except Exception as e:
        return None, str(e)


def check_links(links: dict[str, list[str]]) -> dict[str, list[tuple[str, int | None, str]]]:
    """Check all links and return failures grouped by category."""
    session = requests.Session()
    failures: dict[str, list[tuple[str, int | None, str]]] = {}

    for category, urls in links.items():
        cat_failures = []
        for url in urls:
            status, err = check_url(url, session)
            if status is None or status >= 400:
                cat_failures.append((url, status, err))
        if cat_failures:
            failures[category] = cat_failures

    return failures


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def report(page_url: str, links: dict[str, list[str]], failures: dict[str, list[tuple]]) -> bool:
    """Print results. Returns True if all links OK."""
    total = sum(len(v) for v in links.values())
    total_fail = sum(len(v) for v in failures.values())
    ok = total - total_fail

    print(f"\n{'='*70}")
    print(f"URL: {page_url}")
    print(f"  previews:  {len(links['previews'])}")
    print(f"  json:      {len(links['json'])}")
    print(f"  datasets:  {len(links['datasets'])}")
    print(f"  total:     {total}   ok: {ok}   failed: {total_fail}")

    if not failures:
        print("  All links OK")
        return True

    for category, items in failures.items():
        print(f"\n  [{category}] {len(items)} failing:")
        for url, status, err in items:
            label = str(status) if status is not None else "ERR"
            detail = err if err else ""
            print(f"    {label}  {url}  {detail}")

    return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build_record_urls(base: str, ids: list[int]) -> list[str]:
    base = base.rstrip("/")
    return [f"{base}/data?id={i}" for i in ids]


def fetch_all_record_ids(base: str) -> list[int]:
    """Hit the CDCS data API to get all record IDs."""
    base = base.rstrip("/")
    session = requests.Session()
    ids = []
    page = 1
    while True:
        url = f"{base}/rest/data/?page={page}&page_size=100"
        try:
            resp = session.get(url, verify=False, timeout=15)
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            print(f"Error fetching record list: {e}", file=sys.stderr)
            break
        results = data.get("results", data if isinstance(data, list) else [])
        if not results:
            break
        for r in results:
            ids.append(r["id"])
        if not data.get("next"):
            break
        page += 1
    return ids


def main() -> None:
    parser = argparse.ArgumentParser(description="Check CDCS record resource links for 404s")
    parser.add_argument("url", help="Full record URL (e.g. https://host/data?id=16) or base URL with --all/--ids")
    parser.add_argument("--all", action="store_true", help="Check all records (url should be base URL)")
    parser.add_argument("--ids", help="Comma-separated record IDs to check (url should be base URL)")
    parser.add_argument("--timeout", type=int, default=30, help="Page load timeout in seconds (default 30)")
    args = parser.parse_args()

    if args.all:
        ids = fetch_all_record_ids(args.url)
        if not ids:
            print("No records found.", file=sys.stderr)
            sys.exit(1)
        urls = build_record_urls(args.url, ids)
        print(f"Checking {len(urls)} records...")
    elif args.ids:
        ids = [int(i.strip()) for i in args.ids.split(",")]
        urls = build_record_urls(args.url, ids)
    else:
        urls = [args.url]

    any_failures = False
    for page_url in urls:
        try:
            links = get_page_links(page_url, timeout_ms=args.timeout * 1000)
        except Exception as e:
            print(f"Error rendering {page_url}: {e}", file=sys.stderr)
            any_failures = True
            continue

        failures = check_links(links)
        ok = report(page_url, links, failures)
        if not ok:
            any_failures = True

    print()
    sys.exit(1 if any_failures else 0)


if __name__ == "__main__":
    main()
